### ISSUE TITLE
AttributeError - 'NoneType' object has no attribute 'get_parent'

### ISSUE THREAD

**Issue by andrewebdev** [jberghoef/wagtail-tag-manager#70]
**Describe the bug**
Added application, cookie consent middleware, urls and template tags to my project, as the readme specifies.
I made sure not to include the other middleware since I'm using the template tags directly in the templates.

The tags cause the following traceback however.

**Additional context**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.7/site-packages/wagtail_tag_manager/templatetags/wtm_tags.py", line 108, in wtm_instant_tags
    for tag in TagStrategy(request).result:
  File "/usr/local/lib/python3.7/site-packages/wagtail_tag_manager/strategy.py", line 163, in result
    result = [*self._get_tags_for_request(), *self._get_tags_for_page()]
  File "/usr/local/lib/python3.7/site-packages/wagtail_tag_manager/strategy.py", line 200, in _get_tags_for_page
    while parent.get_parent():

Exception Type: AttributeError at /
Exception Value: 'NoneType' object has no attribute 'get_parent'

```

**Comment by andrewebdev** [comment]
I traced this error and found the reason.

Latest versions of wagtail don't include "site" in the request by default anymore. So the `get_page_for_request()` method needs to change so that it doesn't try to look up site in the request for the latest wagtail:

https://github.com/jberghoef/wagtail-tag-manager/blob/3ccb17887b04d9681741f032e39205277a675143/src/wagtail_tag_manager/utils.py#L89-L98
